### ISSUE TITLE
Example does not work under NodeJs 12

### ISSUE THREAD

**Issue by christofkac** [robertklep/nefit-easy-commands#11]
I'm using your library successfully since a long time in an ioBroker home automation environment. So far I was using NodeJs 10 and have now a parallel installation with NodeJs 12.
When I now execute status.js in the new NodeJs 12 based setup, the function simply does not return.
I use `node status.js`.

I don't know if the NodeJs version is the reason but I don't know any other major difference.
Any chance to debug the situation?
Thanks
Christof

**Comment by robertklep** [comment]
You can try `env DEBUG=* node status.js`

But there shouldn't be a reason why it's not working with v12, unless with "a parallel installation" you mean that you're using a different (newer) Linux distro as well. In which case, this may be relevant: https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions

**Comment by christofkac** [comment]
You're great, indeend my new installation was based on Buster and the fix of openssl.cnf did the job!

> The solution is mentioned here: edit the file /etc/ssl/openssl.cnf and change the following keys to these values:
>
>MinProtocol = None
>CipherString = DEFAULT

Many thanks for the instant support!!!

All the best
Christof
