### ISSUE TITLE
Gasusage API

### ISSUE THREAD

**Issue by RaimondB** [robertklep/nefit-easy-commands#12]
I'd like to use the GasUage commands to get the gas usage for today or maybe yesterday,
Can you point me in the right direction how to use the commands.
I'm getting a bit confused with the paging stuff.

Thanks in advance!

**Comment by robertklep** [comment]
It's documented [here](https://github.com/robertklep/nefit-easy-core/wiki/List-of-endpoints#gas-usage-history). 

In short (and from the top of my head; I don't own a Nefit Easy anymore so can't check): each gas usage page contains 32 entries, which correspond to 32 days. If you run the `gasUsage` command without a specific page index, it will retrieve the latest page (which holds the data for yesterday and the 31 days before that).

If you want to find out how many pages there are, use the `gasUsagePage` command. Pages start with (I think) 1, which contains the oldest data.

**Comment by RaimondB** [comment]
Thanks I have got it working
