### ISSUE TITLE
Increase current temperature

### ISSUE THREAD

**Issue by RaimondB** [robertklep/nefit-easy-commands#6]
I would like to be able to set the temperature x degrees higher than the current temperature, as a way to make sure the CV will start heating in order to manage zonebased heating scenario's for other rooms.

I could build it in to the [node-red-nefit-easy2](https://github.com/RaimondB/node-red-contrib-nefit-easy), but the better place would be this library I think.
What do you think?

I'm thinking that instead of '> 20' and '< 20' one could also have a specifier of '+2.0' or ' -2.0'  as an argument to the setTemperature command

**Comment by robertklep** [comment]
Just published `nefit-easy-commands@3.0.3` which implements this :D 

See [README.md](https://github.com/robertklep/nefit-easy-commands#set-temperature).

**Comment by RaimondB** [comment]
Nice, Is the increase based on the setpoint or the current measured temperature? For my scenario I need it to be based on the current temperature.

**Comment by robertklep** [comment]
Setpoint, I'm afraid. Perhaps currently measured makes more sense, now that I think about it.

**Comment by RaimondB** [comment]
For me it does. but I see that it fits not so well in the current settemperature command. Maybe a separate command that bases actions on current temp would be clearer?

**Comment by robertklep** [comment]
Or perhaps implement a full parser:
```
if (targetTemp < 20) targetTemp = 20
targetTemp = currentTemp + 2.5
```

**Comment by RaimondB** [comment]
I've provided a pull-request with this feature, hope you find it usefull #7 
It is a bit simpler of a solution, which adds t+ and t- specifiers.

**Comment by RaimondB** [comment]
Supported now in 3.0.4
